baseURL = "https://nixos.tokyo/blog/"
languageCode = "ja"
title = "nixos.tokyo blog"
theme = "hugo_theme_robust"

[params]
  Author = "hyphon81"
  disqusShortname = "nixos-tokyo"
  googleAnalytics = "UA-57997520-5"

[outputs]
page = [ "HTML", "AMP" ]